name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - build-apk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'  # Specify your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d"+" -f1)
          echo "version=$version" >> $GITHUB_ENV

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release ${{ env.version }}
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ env.version }}
          tag: ${{ env.version }}